using System;
using System.Collections.Generic;
using System.Data;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Linq;
using System.Text;

namespace MyToolkit.Entities
{
	public interface IInsertEntity
	{
		void OnInserting();
	}

	public interface IUpdateEntity
	{
		void OnUpdating(IList<string> changedProperties);
	}

	public class ExtendedObjectContext : ObjectContext
	{
		/// <summary>
		/// Used in ObjectContext implementations in classes which cannot change the inherited class (e.g. generated by edmx)
		/// </summary>
		/// <param name="ctx"></param>
		public static void SaveChanges(ObjectContext ctx)
		{
			foreach (var e in ctx.ObjectStateManager.GetObjectStateEntries(EntityState.Added))
			{
				var entity = e.Entity as IInsertEntity;
				if (entity != null)
					entity.OnInserting();
			}

			foreach (var e in ctx.ObjectStateManager.GetObjectStateEntries(EntityState.Modified))
			{
				var entity = e.Entity as IUpdateEntity;
				if (entity != null)
					entity.OnUpdating(e.GetModifiedProperties().ToArray());
			}
		}

		public ExtendedObjectContext(EntityConnection connection) : base(connection) { }
		public ExtendedObjectContext(string connectionString) : base(connectionString) { }
		protected ExtendedObjectContext(string connectionString, string defaultContainerName) : base(connectionString, defaultContainerName) { }
		protected ExtendedObjectContext(EntityConnection connection, string defaultContainerName) : base(connection, defaultContainerName) { }

		public override int SaveChanges(SaveOptions options)
		{
			SaveChanges(this);
			return base.SaveChanges(options);
		}

		protected override void Dispose(bool disposing)
		{
			ContextOptions.LazyLoadingEnabled = false; // avoid exceptions on serializing
			base.Dispose(disposing);
		}
	}
}
